# Generated by Django 3.1.3 on 2021-01-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20201204_1557'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bank',
            name='banks_bank_unique_ip_port_proto',
        ),
        migrations.RemoveIndex(
            model_name='bank',
            name='banks_bank_ip_addr_adba75_idx',
        ),
        migrations.AlterField(
            model_name='bank',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
