# Generated by Django 3.1.3 on 2021-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20210108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['ip_address', 'port', 'protocol'], name='banks_bank_ip_addr_adba75_idx'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('ip_address', 'port', 'protocol'), name='banks_bank_unique_ip_port_proto'),
        ),
    ]
