# Generated by Django 3.1.3 on 2021-01-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_auto_20201204_1557'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validator',
            name='validators_validator_unique_ip_port_proto',
        ),
        migrations.RemoveIndex(
            model_name='validator',
            name='validators__ip_addr_d18429_idx',
        ),
        migrations.AlterField(
            model_name='validator',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
