# Generated by Django 3.1.3 on 2021-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0003_auto_20210108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['ip_address', 'port', 'protocol'], name='validators__ip_addr_d18429_idx'),
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.UniqueConstraint(fields=('ip_address', 'port', 'protocol'), name='validators_validator_unique_ip_port_proto'),
        ),
    ]
