# Generated by Django 3.1.8 on 2021-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shift', models.FloatField()),
                ('total', models.IntegerField()),
                ('accounts', models.IntegerField()),
                ('max_balance', models.IntegerField()),
                ('richest', models.CharField(max_length=100)),
                ('top_5_wealth', models.IntegerField()),
                ('top_5_ownership', models.FloatField()),
                ('top_5_accounts', models.IntegerField()),
                ('top_10_wealth', models.IntegerField()),
                ('top_10_ownership', models.FloatField()),
                ('top_10_accounts', models.IntegerField()),
                ('top_25_wealth', models.IntegerField()),
                ('top_25_ownership', models.FloatField()),
                ('top_25_accounts', models.IntegerField()),
                ('top_50_wealth', models.IntegerField()),
                ('top_50_ownership', models.FloatField()),
                ('top_50_accounts', models.IntegerField()),
            ],
        ),
    ]
