# Generated by Django 3.1.3 on 2021-01-08 19:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('delay', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaucetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_user_id', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_valid_access_time', models.DateTimeField(default=datetime.datetime(2021, 1, 9, 3, 39, 21, 418490))),
                ('social_type', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook')], max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.AddIndex(
            model_name='faucetmodel',
            index=models.Index(fields=['next_valid_access_time'], name='tnb_faucet__next_va_63b042_idx'),
        ),
        migrations.AddIndex(
            model_name='faucetmodel',
            index=models.Index(fields=['account', 'social_user_id'], name='tnb_faucet__account_87730e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faucetmodel',
            unique_together={('social_type', 'social_user_id')},
        ),
    ]
