# Generated by Django 3.1.3 on 2021-01-16 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210108_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook')], max_length=8)),
                ('social_user_id', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('next_valid_access_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='FaucetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('delay', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tnb_faucet.faucetoption')),
                ('social_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnb_faucet.faucetmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=models.Index(fields=['post_id'], name='tnb_faucet__post_id_861c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postmodel',
            unique_together={('post_id', 'social_user')},
        ),
        migrations.AddIndex(
            model_name='faucetmodel',
            index=models.Index(fields=['next_valid_access_time'], name='tnb_faucet__next_va_63b042_idx'),
        ),
        migrations.AddIndex(
            model_name='faucetmodel',
            index=models.Index(fields=['account', 'social_user_id'], name='tnb_faucet__account_87730e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faucetmodel',
            unique_together={('social_user_id', 'account'), ('social_type', 'social_user_id'), ('social_type', 'account')},
        ),
    ]