# Generated by Django 3.1.3 on 2021-01-08 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnb_faucet', '0002_auto_20210108_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetmodel',
            name='next_valid_access_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 22, 49, 5, 881048)),
        ),
    ]
