# Generated by Django 3.1.3 on 2021-01-08 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnb_faucet', '0006_auto_20210108_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetmodel',
            name='next_valid_access_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 0, 15, 41, 596410)),
        ),
    ]
