# Generated by Django 3.1.3 on 2021-01-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnb_faucet', '0008_auto_20210108_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetmodel',
            name='next_valid_access_time',
            field=models.DateTimeField(),
        ),
    ]
